[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "postgresql"]

[phases.install]
cmds = ["pip install --user -r requirements.txt"]

[start]
cmd = "PYTHONPATH=$HOME/.local/lib/python3.10/site-packages python manage.py runserver 0.0.0.0:$PORT"