# Generated by Django 5.2 on 2025-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='ticket_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
