# Generated by Django 5.2 on 2025-04-11 04:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_contactmessage_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
